### ISSUE TITLE
Where has `CachedBundleDependenciesResolver` gone?

### ISSUE THREAD

**Issue by Toflar** [mmoreram/symfony-bundle-dependencies#8]
According to the README there should be a `CachedBundleDependenciesResolver` trait that has apparently been removed :smile: Was this on purpose because it was not the way you wanted it to be but the README wasn't updated or what's the issue here?

I'm interested in this bundle because we need this for Contao, a CMS based on the full stack framework. 
- We need a caching layer so I wonder why you have deleted it?
- We have a special type of bundle that only requires `string` arguments for the bundle constructor, so they could be cached as well. Would you support such a feature?

I'm willing to provide PR's for all the stuff, just wanted to hear from you why the `CachedBundleDependenciesResolver` has gone? :smile: 
Thank you!

**Comment by mmoreram** [comment]
wops!

you're right! :/

I will add it again tomorrow :'/

Thanks!

**Comment by Toflar** [comment]
No worries :) What about the question regarding instances with fixed arguments? They would be cacheable in theory if we used something like `['Namespace\Class', ['argument_1', 'argument_2']]`? I'll have a look at your implementation first though and then provide a PR :-)

**Comment by Toflar** [comment]
bump :)

**Comment by mmoreram** [comment]
I've added this PR

https://github.com/mmoreram/symfony-bundle-dependencies/pull/10

This PR reverses https://github.com/mmoreram/symfony-bundle-dependencies/commit/f5edb7002c905b01208724719e0e5d1bbd10d1a0 due to BC Break, so, and because we can cache the result of the dependencies inspection, we will take some time in order to redo this PR.

ping @xphere

**Comment by xphere** [comment]
To add your own cache layer over this is quite simple: don't use `resolveAndReturnBundleDependencies` from the `BundleDependenciesResolver` trait. Just create an instance of `BundleDependenciesResolver` and decorate it with any cache you want.

If you ask me, I don't think this bundle should be responsible for this cache layer.

**Comment by aschempp** [comment]
Can you tell me a reason why anyone would **not** want to cache the result?

**Comment by xphere** [comment]
I don't see what's the point to cache always this result. We're using this without cache and it's blazingly fast. I can't think of a cache layer which will add better performance to the process.

But even if it were slow as hell, it's not the responsibility of this bundle to cache the result. What technology would you use under the hood? Redis? And for people not having Redis? Would you create an interface for that?

I can only think of a cache layer that can be of use: writing the resulting array to a `.php` file and create it in the cache warm up.

**Comment by aschempp** [comment]
> I can only think of a cache layer that can be of use: writing the resulting array to a .php file and create it in the cache warm up.

That's what the current implementation actually does. And any command (e.g. `cache:warmup`) would boot the kernel and therefore create the cache.
